### PR TITLE
Updated to work with flu_ani module

### PR DESCRIPTION
**Pull request by mariuszlas**
Several functions were slightly modified or new features were added so that this module can be used with the fluorescence anisotropy package.

List of changes:
1. In the 'invalidate_cols' function the mechanism of generating all well ids from scratch was replaced with taking them from the platemap index, those are later used to create a list of well ids to be invalidated based on the columns to be invalidated.
2. In 'labelwell' function an option was added to format the number in scientific notation.
3. In 'fontsize' function an option was added to calculate the font size based on a parameter passed (str_len) if the value is to be displayed in scientific notation to avoid calculating it based on the length of original float which gives incorrect result.
4.  In 'visualise' function two parameters were added: 'scinot' and 'str_len' that are passed to labelwell and fontsize functions. Also, in order to generate subplots for all well ids, the function now iterates over a list of tuples (each one containing a row number corresponding to a specified row letter and a column number) used to place the subplot on a grid. There is no need to use the 'Row' and 'Column' columns which are absent in the fluorescence anisotropy platemaps.
5. The header_names_short and header_names_long lists and the data_types dictionary were removed and their information is now sorted in the header_names dictionary.
6. In 'empty_map' function the mechanism of generating the well ids was updated removing the need for 'Row' and 'Column' columns in the platemap.
7. In 'plate_map' function trailing spaces removal mechanism was updated to avoid an error if the platemap csv file has a column with all cells 'NaN'.

### CODE REVIEW

**Comment by lawrencecollins** [comment]
Hi Mariusz, 

Really happy to see this module is coming in handy! I hope you are finding my novice coding alright to work with! I was just checking to see whether this can be merged but I think there might be a couple of syntax errors (check line 55 and line 70). There are also some undefined variables (product, header_names_long and header_names_short) which seem to stop it from working. 

Other than that it looks fab, much tidier and it's great that it can now be used with other sorts of data!

Thanks, 
Lawrence

**Comment by lawrencecollins** [comment]
P.S. I'd really recommend editing modules in an IDE like Visual Studio Code, it has built in debugging using stuff like Pylint, really helps to find any issues that might otherwise take days to find

**Comment by mariuszlas** [comment]
Hi Lawrence,

Your plate mapping module is useful indeed and really saved us some time. I corrected the syntax errors and resolved the problem with undefined variables (product, header_names_long and header_names_short) in the latest commit. I hope it will work now, but if there are any issues, do let me know. Also, thanks for the tip with IDE.

Mariusz

**Comment by lawrencecollins** [comment]
Nice one, it's looking better but there's still an undefined variable on line 120

**Comment by mariuszlas** [comment]
Corrected

**Comment by lawrencecollins** [comment]
Great, looks like my calcium flex module is a little confused by the changes, I'll have a look into it a bit later to see what the problem is

**Comment by lawrencecollins** [comment]
Have you got a copy of the updated plate map template?

**Comment by mariuszlas** [comment]
Here is a kind plate map we would use for [fluorescence anisotropy 
](https://github.com/mariuszlas/Automation-of-Fluorescence-Anisotropy-Binding-Data-Processing/blob/main/fluorescenceanisotropy/plate_map.csv)

**Pull request merged**
